[tool.poetry]
name = "django-email-user"
version = "0.1.0"
description = "Custom, simple Django User model with only email and name fields"
authors = ["Khasbilegt.TS <khasbilegt.ts@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.7"

[tool.poetry.dev-dependencies]
factory-boy = "^3.2.0"
black = "^21.9b0"
flake8 = "^3.9.2"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
